# Generated by Django 4.2.7 on 2023-11-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dazzle', '0002_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
